# Generated by Django 2.0.1 on 2018-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název')),
                ('akreditace_msmt', models.BooleanField(verbose_name='Akreditace MŠMT')),
                ('hodin', models.PositiveSmallIntegerField(verbose_name='Počet hodin')),
                ('misto', models.CharField(max_length=100, verbose_name='Místo konání')),
                ('termin', models.CharField(max_length=200, verbose_name='Termín konání')),
                ('lektor', models.CharField(max_length=80)),
                ('min_ucastniku', models.PositiveSmallIntegerField(verbose_name='Minimální počet účastníků')),
                ('max_ucastniku', models.PositiveSmallIntegerField(verbose_name='Maximální počet účastníků')),
                ('opakovani', models.BooleanField(verbose_name='Opakování')),
            ],
        ),
    ]
