# Generated by Django 2.0.1 on 2018-01-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurzy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kurz',
            new_name='Kurzy',
        ),
    ]
