# Generated by Django 2.0.1 on 2018-01-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurzy', '0003_auto_20180120_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurzy',
            name='akreditace_msmt',
        ),
        migrations.AddField(
            model_name='kurzy',
            name='akreditace_mpsv',
            field=models.BooleanField(default=False, verbose_name='Akreditace MPSV'),
            preserve_default=False,
        ),
    ]
