# Generated by Django 2.0.1 on 2018-01-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=40, verbose_name='Přezdívka')),
                ('display_name', models.CharField(max_length=100, verbose_name='Zobrazované jméno')),
                ('full_name', models.CharField(max_length=130, verbose_name='Úplné jméno')),
                ('patronci_vztah', models.CharField(choices=[('Předseda', 'Předseda'), ('Zakládající člen', 'Zakládající člen'), ('Běžný člen', 'Běžný člen')], max_length=50, verbose_name='Vztah k Patronce')),
                ('motto', models.CharField(max_length=200, verbose_name='Motto')),
                ('patronci_zajmy', models.TextField(verbose_name='Patrončí zájmy')),
                ('pracovni_zkusenosti', models.TextField(verbose_name='Pracovní zkušenosti')),
            ],
        ),
    ]
