# Generated by Django 2.0.1 on 2018-01-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0004_auto_20180121_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='clenove',
            name='foto',
            field=models.ImageField(null=True, upload_to='clenove_foto/'),
        ),
    ]
